name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      package:
          type: string
          description: "Package ID"
          required: true
          default: "com.android.example"
      min_sdk:
          type: choice
          options: [ 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1 ]
          description: "Min sdk"
          required: true
          default: "21"
      app_name:
          type: string
          description: "App name"
          required: false
          default: ""
      sign:
          type: boolean
          description: Custom signing
          required: true
          default: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Apply custom names
        run: |
          # Set package ID
          if [ "${{ inputs.package }}" != "" ]; then
            sed -i -e 's/package=\"com.android.example/package=\"${{ inputs.package }}/' AndroidManifest.xml
          fi
          # Set app name
          if [ "${{ inputs.app_name }}" != "" ]; then
            sed -i -e 's/label=\"/label=\"${{ inputs.app_name }}/' AndroidManifest.xml
          else
            sed -i -e '/label=/d' AndroidManifest.xml
          fi

      - name: Setup custom signature
        if: ${{ inputs.sign }}
        run: |
          echo "${{ secrets.CERT }}" > data/cert.pem
          echo "${{ secrets.KEY }}" | base64 -d > data/cert.pk8

      - name: Make
        run: |
          export PATH=$PATH:$ANDROID_HOME/build-tools/35.0.1
          ./build.sh "${{ inputs.min_sdk }}"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "stub"
          path: "stub.apk"
